# mysql
spring:
  datasource:
    # mysql configuration
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.135:3306/vsep?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: zksmysql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

server:
  port: 9000
logging:
#  level: debug
  file:
    path: D:/test.log

